FROM me-central2-docker.pkg.dev/sao-prj-shr-30049727-ar-0/shr-30049727-dkr-vrt-0/aramco.com/node:24 AS base
WORKDIR /app

COPY package*.json tsconfig.json ./
RUN npm install

COPY . .
RUN npm run build:qa

FROM me-central2-docker.pkg.dev/sao-prj-shr-30049727-ar-0/shr-30049727-dkr-vrt-0/chainguard/nginx:latest
ARG COMMIT_SHA
ARG BUILD_ID
LABEL COMMIT_SHA=${COMMIT_SHA}
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=base /app/dist/cms-vendor-frontend/browser /usr/share/nginx/html
EXPOSE 8081
CMD ["nginx", "-g", "daemon off;"]

